version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: sic_portal_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cmjqgkmy_majra_sic
      MYSQL_USER: cmjqgkmy_majra_sic_admin
      MYSQL_PASSWORD: +J~Pj!L277Q^
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

volumes:
  db_data:
