version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: sic_portal_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sic_portal
      MYSQL_USER: sic_user
      MYSQL_PASSWORD: sic_password
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

volumes:
  db_data:
